import User from "../../../images/avatar/b-sm.jpg";
import User2 from "../../../images/avatar/c-sm.jpg";
import User3 from "../../../images/avatar/a-sm.jpg";
import User4 from "../../../images/avatar/d-sm.jpg";

export const customerData = [
  {
    id: "UD01544",
    Firstname: "Abu Bin",
    Lastname: "Ishtiyak",
    BVN: "22345664",
    account: "23243444",
    avatarBg: "primary",
    doc: "Passport",
    check: false,
    front: true,
    back: true,
    date: "18 Dec, 2019 01:02 PM",
    status: "Approved",
    checked: "Janet Snyder",
    Level: "1",
  },
  {
    id: "UD01489",
    Firstname: "Amelia ",
    Lastname: "Grant",
    BVN: "22345664",
    account: "232536444",
    image: User3,
    avatarBg: "primary",
    check: false,
    doc: "NationalID",
    front: true,
    back: true,
    date: "12 Jan, 2020 01:02 PM",
    status: "Approved",
    checked: "Ernesto Vargas",
    Level: "2",
  },
  {
    id: "UD01434",
    Firstname: "Kristen ",
    Lastname: "Hawkins",
    BVN: "22345664",
    account: "23243784",
    avatarBg: "primary",
    image: User,
    doc: "Passport",
    check: false,
    front: true,
    back: true,
    date: "18 Dec, 2019 01:02 PM",
    status: "Approved",
    checked: "Ernesto Vargas",
    Level: "3",
  },
  {
    id: "UD01286",
    Firstname: "Tommy ",
    Lastname: "Vasquez",
    BVN: "22345664",
    account: "23243784",
    avatarBg: "purple",
    doc: "Driving ID",
    front: true,
    check: false,
    back: false,
    date: "12 Jan, 2020 01:02 PM",
    status: "Pending",
    checked: "Ernesto Vargas",
    Level: "2",
  },
  {
    id: "UD01235",
    Firstname: "Alejandro ",
    Lastname: "Haynes",
    BVN: "22345664",
    account: "22543444",
    avatarBg: "teal",
    doc: "Passport",
    check: false,
    front: true,
    back: true,
    date: "18 Dec, 2019 01:02 PM",
    status: "Approved",
    checked: "Janet Snyder",
    Level: "3",
  },
  {
    id: "UD01223",
    Firstname: "Brooke ",
    Lastname: "Harmon",
    BVN: "22345664",
    account: "28243444",
    avatarBg: "primary",
    image: User4,
    doc: "Passport",
    check: false,
    front: true,
    back: true,
    date: "18 Dec, 2019 01:02 PM",
    status: "Rejected",
    checked: "Janet Snyder",
    Level: "1",
  },
  {
    id: "UD01124",
    Firstname: "Trevor ",
    Lastname: "Miller",
    BVN: "22345664",
    account: "25243444",
    avatarBg: "gray",
    doc: "Passport",
    check: false,
    front: true,
    back: true,
    date: "10 Jan, 2020 01:02 PM",
    status: "Approved",
    checked: "Ernesto Vargas",
    Level: "2",
  },
  {
    id: "UD01120",
    Firstname: "Lonnie ",
    Lastname: "Ferguson",
    BVN: "22345664",
    account: "21243444",
    avatarBg: "primary",
    image: User2,
    doc: "Driving ID",
    check: false,
    front: true,
    back: false,
    date: "03 Jan, 2020 12:45 AM",
    status: "Pending",
    checked: "Ernesto Vargas",
    Level: "1",
  },
  {
    id: "UD00954",
    Firstname: "Mack  ",
    Lastname: "Kennedy",
    BVN: "22345664",
    account: "23249444",
    avatarBg: "teal",
    doc: "Passport",
    check: false,
    front: true,
    back: true,
    date: "18 Nov, 2019 01:02 PM",
    status: "Approved",
    checked: "Janet Snyder",
    Level: "3",
  },
  {
    id: "UD00472",
    Firstname: "Zia ",
    Lastname: "Burkett",
    BVN: "22345664",
    account: "23243466",
    avatarBg: "danger",
    doc: "Passport",
    check: false,
    front: true,
    back: false,
    date: "12 Nov, 2019 01:02 AM",
    status: "Rejected",
    checked: "Janet Snyder",
    Level: "2",
  },
  {
    id: "UD01734",
    Firstname: "Ferdinand ",
    Lastname: "Grant",
    BVN: "22345664",
    account: "232438944",
    avatarBg: "primary",
    image: User,
    doc: "Passport",
    check: false,
    front: true,
    back: true,
    date: "18 Dec, 2019 01:02 PM",
    status: "Approved",
    checked: "Ernesto Vargas",
    Level: "1",
  },
  {
    id: "UD02020",
    Firstname: "Inez ",
    Lastname: "Wilkerson",
    BVN: "22345664",
    account: "23243448",
    avatarBg: "warning",
    doc: "Passport",
    check: false,
    front: true,
    back: false,
    date: "12 Nov, 2019 01:02 AM",
    status: "Rejected",
    checked: "Janet Snyder",
    Level: "3",
  }, //new
  {
    id: "UD02021",
    Firstname: "Alyana",
    Lastname: "Thomson",
    BVN: "22345664",
    account: "232434674",
    avatarBg: "danger",
    doc: "Passport",
    check: false,
    front: true,
    back: false,
    date: "12 Nov, 2019 01:02 AM",
    status: "Approved",
    checked: "Janet Snyder",
    Level: "2",
  },
  {
    id: "UD02022",
    Firstname: "Alexa ",
    Lastname: "Rollins",
    BVN: "22345664",
    account: "23243494",
    avatarBg: "pink",
    doc: "Passport",
    check: false,
    front: true,
    back: false,
    date: "12 Nov, 2019 01:02 AM",
    status: "Approved",
    checked: "Ernesto Vargas",
    Level: "3",
  },
  {
    id: "UD02023",
    Firstname: "Moira",
    Lastname: " Baxter",
    BVN: "22345664",
    account: "23243474",
    avatarBg: "blue",
    doc: "Passport",
    check: false,
    front: true,
    back: false,
    date: "12 Nov, 2019 01:02 AM",
    status: "Pending",
    checked: "Ernesto Vargas",
    Level: "2",
  },
  {
    id: "UD02024",
    Firstname: "Irma Rogers",
    Lastname: "Grant",
    BVN: "22345664",
    account: "232673444",
    avatarBg: "success",
    doc: "Driving Id",
    check: false,
    front: true,
    back: false,
    date: "12 Nov, 2019 01:02 AM",
    status: "Pending",
    checked: "Ernesto Vargas",
    Level: "2",
  },
  {
    id: "UD02025",
    Firstname: "Candice ",
    Lastname: "Wu",
    BVN: "22345664",
    account: "20243444",
    avatarBg: "purple",
    doc: "Driving Id",
    check: false,
    front: true,
    back: false,
    date: "12 Nov, 2019 01:02 AM",
    status: "Approved",
    checked: "Ernesto Vargas",
    Level: "1",
  },
  {
    id: "UD02026",
    Firstname: "Jane",
    Lastname: "Calvert",
    BVN: "22345664",
    account: "237853444",
    avatarBg: "warning",
    doc: "Passport",
    check: false,
    front: true,
    back: false,
    date: "12 Nov, 2019 01:02 AM",
    status: "Rejected",
    checked: "Ernesto Vargas",
    Level: "2",
  },
];

export const filterStatus = [
  { value: "approved", label: "Approved" },
  { value: "pending", label: "Pending" },
  { value: "deleted", label: "Deleted" },
  { value: "rejected", label: "Rejected" },
];

export const filterDoc = [
  { value: "nid", label: "Nidcard" },
  { value: "passport", label: "Passport" },
  { value: "driving", label: "Driving" },
];

export const bulkActionKycOptions = [
  { value: "Reject", label: "Reject" },
  { value: "Delete", label: "Delete" },
];
